services:
  postgres:
    image: 'postgres:latest'
    container_name: upbanktracker-db
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=upbanktracker-db
    volumes:
      - ./var/db-data/:/var/lib/postgresql/data/
